Traceback (most recent call last):
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/runner/micromamba-root/envs/cordex-tutorials/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import fsspec
import xarray as xr

ds = xr.open_zarr(
    store=fsspec.get_mapper(cordex, anon=True),
    consolidated=True,
)
ds
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mfsspec[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mxarray[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxr[39;00m
[1;32m      4[0m ds [38;5;241m=[39m xr[38;5;241m.[39mopen_zarr(
[0;32m----> 5[0m     store[38;5;241m=[39mfsspec[38;5;241m.[39mget_mapper([43mcordex[49m, anon[38;5;241m=[39m[38;5;28;01mTrue[39;00m),
[1;32m      6[0m     consolidated[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m      7[0m )
[1;32m      8[0m ds

[0;31mNameError[0m: name 'cordex' is not defined

